name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: pnpm

      - name: 安装pnpm
        run: pnpm install

      - name: 执行Lint
        run: pnpm run lint

  automerge:
    needs: ci
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@main
        with:
          github-token: ${{ github.token }}
          target: minor
